## Monitor API

### Create a monitor
POST http://localhost:3000/api/monitors
Content-Type: application/json

{
  "name": "Google",
  "url": "https://www.google.com",
  "interval": 300
}


### Get all monitors
GET http://localhost:3000/api/monitors

### Get a monitor by ID
GET http://localhost:3000/api/monitors/099131c6-b3b2-42a4-90c6-6964edba9262

### Update a monitor
PUT http://localhost:3000/api/monitors/d6081333-537f-4fb2-bfbe-c27a0ebc4b4c
Content-Type: application/json

{
  "name": "Google",
  "url": "https://www.google.com",
  "interval": 1500
}

### Delete a monitor
DELETE http://localhost:3000/api/monitors/d6081333-537f-4fb2-bfbe-c27a0ebc4b4c